-- =====================================================
-- MONVANA BANK - DISABLE ROW LEVEL SECURITY (RLS)
-- Migration: 035_disable_rls.sql
-- Description: Disables RLS on all tables to ensure no policies block API queries/inserts
-- =====================================================

ALTER TABLE IF EXISTS public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.wallets DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.billing_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.loans DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.investment_plans DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.investments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.charities DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.donations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.virtual_cards DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.crypto_addresses DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.bank_info DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.referrals DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.favorite_contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.loan_applications DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.loan_documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.bank_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.exchange_rates DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.deposit_methods DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.otps DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.admin_emails DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.kyc_submissions DISABLE ROW LEVEL SECURITY;
